# Generated by Django 3.0.7 on 2020-09-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '0002_auto_20200903_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('short_text', models.TextField(default='-', null=True)),
                ('body_text', models.TextField(default='-', null=True)),
                ('date', models.DateTimeField(null=True)),
                ('picname', models.TextField(blank=True, null=True)),
                ('picurl', models.TextField(blank=True, default='-', null=True)),
                ('writer', models.CharField(max_length=100, null=True)),
                ('catname', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('show', models.IntegerField(blank=True, default=0, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategory.SubCategory')),
            ],
        ),
    ]
