# Generated by Django 3.0.7 on 2020-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
