# Generated by Django 3.0.7 on 2021-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailorphone', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
