# Generated by Django 3.0.7 on 2020-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
