# Generated by Django 3.0.7 on 2020-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
