# Generated by Django 3.0.7 on 2020-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200808_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
