# Generated by Django 3.0.7 on 2020-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200808_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
