# Generated by Django 3.0.7 on 2020-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200811_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
