# Generated by Django 3.0.7 on 2020-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200915_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about_text',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
