# Generated by Django 3.0.7 on 2021-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_main_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200, null=True)),
                ('menu_url', models.CharField(max_length=255, null=True)),
                ('parent', models.IntegerField(max_length=100, null=True)),
                ('position', models.IntegerField(max_length=0, null=True)),
                ('menu_icon', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
